name: build-and-deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out main
              uses: actions/checkout@v4

            - name: Run build
              run: |
                  npm ci
                  npm run build

            - name: Upload build artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist

    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to Pages
              id: deployment
              uses: actions/deploy-pages@v4
